# Generated by Django 3.1.2 on 2020-11-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=70, null=True)),
                ('phone', models.CharField(blank=True, max_length=70, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawName', models.CharField(blank=True, max_length=100, null=True)),
                ('lawDescription', models.CharField(blank=True, max_length=10000, null=True)),
                ('lawImage', models.FileField(blank=True, null=True, upload_to='lawImage')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Practices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practiceName', models.CharField(blank=True, max_length=100, null=True)),
                ('practiceDesc', models.CharField(blank=True, max_length=10000, null=True)),
                ('practiceImage', models.FileField(blank=True, null=True, upload_to='practiceImage')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(blank=True, max_length=100, null=True)),
                ('serviceDesc', models.CharField(blank=True, max_length=10000, null=True)),
                ('serviceImage', models.FileField(blank=True, null=True, upload_to='serviceImage')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
