# Generated by Django 3.1.2 on 2020-11-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_telnet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='law',
            old_name='lawDescription',
            new_name='lawDesc',
        ),
    ]
