# Generated by Django 3.1.2 on 2020-11-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_telnet', '0002_auto_20201120_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaTitle', models.CharField(blank=True, max_length=1000, null=True)),
                ('mediaDesc', models.CharField(blank=True, max_length=10000, null=True)),
                ('byName', models.CharField(blank=True, max_length=100, null=True)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('mediaImage', models.FileField(blank=True, null=True, upload_to='mediaImage')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
