# Generated by Django 3.1.2 on 2020-11-21 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_telnet', '0004_media_related'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('phone', models.CharField(blank=True, max_length=70, null=True)),
                ('commentDesc', models.CharField(blank=True, max_length=100000, null=True)),
                ('commentDate', models.DateField(auto_now_add=True, null=True)),
                ('commentReply', models.CharField(blank=True, max_length=100000, null=True)),
                ('commentReplyDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('mediaId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediaId', to='lawyer_telnet.media')),
            ],
        ),
    ]
